sudo: required

services:
- docker

before_install:
- VERSION=1.3.5

script:
- docker build -t wisecloud/k8s-keepalived:$VERSION .

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && docker push wisecloud/k8s-keepalived:$VERSION
  on:
    all_branches: true
    #condition: "$TRAVIS_BRANCH =~ ^v[0-9]+\\.[0-9]+(\\.[0-9]+)?(-\\S*)?$"
